version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPRE_CLIENT_ROOT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9892"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://0.0.0.0:9892"
      KAFKA_OFFSET_TOPIC_RELICATION_FATOR: 1
    ports:
      - "9892:9892"
